-- CookFlow Seed Data
-- Run this in Supabase SQL Editor after running schema.sql

-- Insert ingredient categories
INSERT INTO ingredient_categories (id, name, icon, color_class) VALUES
('vegetables', 'Vegetables', '🥬', 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300'),
('fruits', 'Fruits', '🍎', 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300'),
('dairy', 'Dairy & Eggs', '🥛', 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300'),
('grains', 'Grains & Pasta', '🌾', 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300'),
('spices', 'Spices & Herbs', '🌿', 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300'),
('proteins', 'Proteins', '🥩', 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300'),
('sauces', 'Sauces & Condiments', '🫙', 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300'),
('other', 'Other', '📦', 'bg-warm-100 text-charcoal-700 dark:bg-charcoal-800 dark:text-warm-300')
ON CONFLICT (id) DO NOTHING;

-- Insert cuisines
INSERT INTO cuisines (id, name, icon, color_class) VALUES
('indian', 'Indian', '🍛', 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300'),
('italian', 'Italian', '🍝', 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300'),
('chinese', 'Chinese', '🥢', 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300'),
('mexican', 'Mexican', '🌮', 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300'),
('korean', 'Korean', '🥘', 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300'),
('american', 'American', '🍔', 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300'),
('mediterranean', 'Mediterranean', '🫒', 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300'),
('japanese', 'Japanese', '🍣', 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300'),
('thai', 'Thai', '🌰', 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300'),
('continental', 'Continental', '🍽️', 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300')
ON CONFLICT (id) DO NOTHING;

-- Insert categories
INSERT INTO categories (id, name, icon, type) VALUES
('breakfast', 'Breakfast', '🥞', 'meal'),
('lunch', 'Lunch', '🍱', 'meal'),
('dinner', 'Dinner', '🍽️', 'meal'),
('snacks', 'Snacks', '🥜', 'meal'),
('desserts', 'Desserts', '🍰', 'meal'),
('drinks', 'Drinks', '🥤', 'meal'),
('vegetarian', 'Vegetarian', '🌱', 'diet'),
('vegan', 'Vegan', '🌿', 'diet'),
('gluten-free', 'Gluten Free', '🌾', 'diet'),
('healthy', 'Healthy', '🥗', 'style'),
('quick', 'Quick & Easy', '⚡', 'style'),
('non-vegetarian', 'Non-Vegetarian', '🍖', 'diet')
ON CONFLICT (id) DO NOTHING;

-- Insert difficulties
INSERT INTO difficulties (id, name, color_class, sort_order) VALUES
('easy', 'Easy', 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300', 1),
('medium', 'Medium', 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300', 2),
('hard', 'Hard', 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300', 3)
ON CONFLICT (id) DO NOTHING;

-- Insert tags
INSERT INTO tags (name) VALUES
('popular'), ('vegetarian'), ('vegan'), ('healthy'), ('quick'), ('spicy'), ('non-vegetarian'),
('breakfast'), ('lunch'), ('dinner'), ('comfort-food'), ('high-protein'), ('budget-friendly'),
('15-minutes'), ('30-minutes'), ('one-pot'), ('meal-prep'), ('kid-friendly'), ('gluten-free'),
('low-carb'), ('keto'), ('dairy-free'), ('nut-free'), ('party'), ('weeknight')
ON CONFLICT (name) DO NOTHING;

-- Insert ingredients (canonical names)
INSERT INTO ingredients (name, category, unit_type, canonical_name) VALUES
-- Vegetables
('onion', 'vegetables', 'count', 'onion'),
('garlic', 'vegetables', 'count', 'garlic'),
('ginger', 'vegetables', 'weight', 'ginger'),
('tomato', 'vegetables', 'count', 'tomato'),
('potato', 'vegetables', 'weight', 'potato'),
('carrot', 'vegetables', 'weight', 'carrot'),
('bell pepper', 'vegetables', 'count', 'bell pepper'),
('spinach', 'vegetables', 'weight', 'spinach'),
('broccoli', 'vegetables', 'weight', 'broccoli'),
('cauliflower', 'vegetables', 'weight', 'cauliflower'),
('mushroom', 'vegetables', 'weight', 'mushroom'),
('zucchini', 'vegetables', 'weight', 'zucchini'),
('eggplant', 'vegetables', 'weight', 'eggplant'),
('cucumber', 'vegetables', 'count', 'cucumber'),
('lettuce', 'vegetables', 'weight', 'lettuce'),
('green onion', 'vegetables', 'count', 'green onion'),
('cilantro', 'vegetables', 'weight', 'cilantro'),
('mint', 'vegetables', 'weight', 'mint'),
('basil', 'vegetables', 'weight', 'basil'),
('parsley', 'vegetables', 'weight', 'parsley'),
('chili', 'vegetables', 'count', 'chili'),
('jalapeño', 'vegetables', 'count', 'jalapeño'),
('red onion', 'vegetables', 'count', 'red onion'),
('shallot', 'vegetables', 'count', 'shallot'),
('celery', 'vegetables', 'count', 'celery'),
('leek', 'vegetables', 'count', 'leek'),
('asparagus', 'vegetables', 'weight', 'asparagus'),
('green bean', 'vegetables', 'weight', 'green bean'),
('pea', 'vegetables', 'weight', 'pea'),
('corn', 'vegetables', 'weight', 'corn'),
('pumpkin', 'vegetables', 'weight', 'pumpkin'),
('sweet potato', 'vegetables', 'weight', 'sweet potato'),
('radish', 'vegetables', 'weight', 'radish'),
('beetroot', 'vegetables', 'weight', 'beetroot'),
('fennel', 'vegetables', 'weight', 'fennel'),
('artichoke', 'vegetables', 'count', 'artichoke'),
('kale', 'vegetables', 'weight', 'kale'),
('arugula', 'vegetables', 'weight', 'arugula'),
('bok choy', 'vegetables', 'weight', 'bok choy'),
('napa cabbage', 'vegetables', 'weight', 'napa cabbage'),
('bitter gourd', 'vegetables', 'weight', 'bitter gourd'),
('drumstick', 'vegetables', 'weight', 'drumstick'),
('curry leaves', 'vegetables', 'weight', 'curry leaves'),
-- Fruits
('lemon', 'fruits', 'count', 'lemon'),
('lime', 'fruits', 'count', 'lime'),
('orange', 'fruits', 'count', 'orange'),
('apple', 'fruits', 'count', 'apple'),
('banana', 'fruits', 'count', 'banana'),
('mango', 'fruits', 'count', 'mango'),
('pineapple', 'fruits', 'weight', 'pineapple'),
('coconut', 'fruits', 'count', 'coconut'),
('avocado', 'fruits', 'count', 'avocado'),
('pomegranate', 'fruits', 'count', 'pomegranate'),
('tamarind', 'fruits', 'weight', 'tamarind'),
-- Dairy & Eggs
('milk', 'dairy', 'volume', 'milk'),
('butter', 'dairy', 'weight', 'butter'),
('ghee', 'dairy', 'weight', 'ghee'),
('cheese', 'dairy', 'weight', 'cheese'),
('mozzarella', 'dairy', 'weight', 'mozzarella'),
('cheddar', 'dairy', 'weight', 'cheddar'),
('parmesan', 'dairy', 'weight', 'parmesan'),
('feta', 'dairy', 'weight', 'feta'),
('ricotta', 'dairy', 'weight', 'ricotta'),
('yogurt', 'dairy', 'volume', 'yogurt'),
('heavy cream', 'dairy', 'volume', 'heavy cream'),
('sour cream', 'dairy', 'volume', 'sour cream'),
('cream cheese', 'dairy', 'weight', 'cream cheese'),
('paneer', 'dairy', 'weight', 'paneer'),
('egg', 'dairy', 'count', 'egg'),
-- Grains & Pasta
('rice', 'grains', 'weight', 'rice'),
('basmati rice', 'grains', 'weight', 'basmati rice'),
('jasmine rice', 'grains', 'weight', 'jasmine rice'),
('brown rice', 'grains', 'weight', 'brown rice'),
('pasta', 'grains', 'weight', 'pasta'),
('spaghetti', 'grains', 'weight', 'spaghetti'),
('penne', 'grains', 'weight', 'penne'),
('fettuccine', 'grains', 'weight', 'fettuccine'),
('lasagna sheets', 'grains', 'weight', 'lasagna sheets'),
('noodles', 'grains', 'weight', 'noodles'),
('rice noodles', 'grains', 'weight', 'rice noodles'),
('egg noodles', 'grains', 'weight', 'egg noodles'),
('udon', 'grains', 'weight', 'udon'),
('ramen noodles', 'grains', 'weight', 'ramen noodles'),
('bread', 'grains', 'count', 'bread'),
('naan', 'grains', 'count', 'naan'),
('roti', 'grains', 'count', 'roti'),
('paratha', 'grains', 'count', 'paratha'),
('tortilla', 'grains', 'count', 'tortilla'),
('pita', 'grains', 'count', 'pita'),
('flour', 'grains', 'weight', 'flour'),
('cornmeal', 'grains', 'weight', 'cornmeal'),
('semolina', 'grains', 'weight', 'semolina'),
('quinoa', 'grains', 'weight', 'quinoa'),
('couscous', 'grains', 'weight', 'couscous'),
('oats', 'grains', 'weight', 'oats'),
('barley', 'grains', 'weight', 'barley'),
-- Spices & Herbs
('salt', 'spices', 'weight', 'salt'),
('black pepper', 'spices', 'weight', 'black pepper'),
('cumin', 'spices', 'weight', 'cumin'),
('coriander', 'spices', 'weight', 'coriander'),
('turmeric', 'spices', 'weight', 'turmeric'),
('chili powder', 'spices', 'weight', 'chili powder'),
('red chili powder', 'spices', 'weight', 'red chili powder'),
('paprika', 'spices', 'weight', 'paprika'),
('smoked paprika', 'spices', 'weight', 'smoked paprika'),
('cayenne', 'spices', 'weight', 'cayenne'),
('garam masala', 'spices', 'weight', 'garam masala'),
('curry powder', 'spices', 'weight', 'curry powder'),
('chaat masala', 'spices', 'weight', 'chaat masala'),
('amchur', 'spices', 'weight', 'amchur'),
('kasuri methi', 'spices', 'weight', 'kasuri methi'),
('mustard seeds', 'spices', 'weight', 'mustard seeds'),
('cumin seeds', 'spices', 'weight', 'cumin seeds'),
('fennel seeds', 'spices', 'weight', 'fennel seeds'),
('fenugreek seeds', 'spices', 'weight', 'fenugreek seeds'),
('cinnamon', 'spices', 'weight', 'cinnamon'),
('cardamom', 'spices', 'weight', 'cardamom'),
('cloves', 'spices', 'weight', 'cloves'),
('bay leaf', 'spices', 'count', 'bay leaf'),
('star anise', 'spices', 'count', 'star anise'),
('nutmeg', 'spices', 'weight', 'nutmeg'),
('mace', 'spices', 'weight', 'mace'),
('oregano', 'spices', 'weight', 'oregano'),
('thyme', 'spices', 'weight', 'thyme'),
('rosemary', 'spices', 'weight', 'rosemary'),
('sage', 'spices', 'weight', 'sage'),
('dill', 'spices', 'weight', 'dill'),
('tarragon', 'spices', 'weight', 'tarragon'),
('gochugaru', 'spices', 'weight', 'gochugaru'),
('gochujang', 'spices', 'weight', 'gochujang'),
('doenjang', 'spices', 'weight', 'doenjang'),
('doubanjiang', 'spices', 'weight', 'doubanjiang'),
('sichuan peppercorn', 'spices', 'weight', 'sichuan peppercorn'),
('five spice', 'spices', 'weight', 'five spice'),
('white pepper', 'spices', 'weight', 'white pepper'),
-- Proteins
('chicken breast', 'proteins', 'weight', 'chicken breast'),
('chicken thigh', 'proteins', 'weight', 'chicken thigh'),
('chicken wings', 'proteins', 'weight', 'chicken wings'),
('whole chicken', 'proteins', 'weight', 'whole chicken'),
('ground chicken', 'proteins', 'weight', 'ground chicken'),
('beef', 'proteins', 'weight', 'beef'),
('ground beef', 'proteins', 'weight', 'ground beef'),
('beef sirloin', 'proteins', 'weight', 'beef sirloin'),
('beef chuck', 'proteins', 'weight', 'beef chuck'),
('pork', 'proteins', 'weight', 'pork'),
('ground pork', 'proteins', 'weight', 'ground pork'),
('pork belly', 'proteins', 'weight', 'pork belly'),
('bacon', 'proteins', 'weight', 'bacon'),
('lamb', 'proteins', 'weight', 'lamb'),
('fish', 'proteins', 'weight', 'fish'),
('salmon', 'proteins', 'weight', 'salmon'),
('cod', 'proteins', 'weight', 'cod'),
('tilapia', 'proteins', 'weight', 'tilapia'),
('shrimp', 'proteins', 'weight', 'shrimp'),
('prawns', 'proteins', 'weight', 'prawns'),
('scallops', 'proteins', 'weight', 'scallops'),
('mussels', 'proteins', 'weight', 'mussels'),
('clams', 'proteins', 'weight', 'clams'),
('squid', 'proteins', 'weight', 'squid'),
('tofu', 'proteins', 'weight', 'tofu'),
('firm tofu', 'proteins', 'weight', 'firm tofu'),
('silken tofu', 'proteins', 'weight', 'silken tofu'),
('tempeh', 'proteins', 'weight', 'tempeh'),
('chickpeas', 'proteins', 'weight', 'chickpeas'),
('black beans', 'proteins', 'weight', 'black beans'),
('kidney beans', 'proteins', 'weight', 'kidney beans'),
('lentils', 'proteins', 'weight', 'lentils'),
('red lentils', 'proteins', 'weight', 'red lentils'),
('moong dal', 'proteins', 'weight', 'moong dal'),
('toor dal', 'proteins', 'weight', 'toor dal'),
('chana dal', 'proteins', 'weight', 'chana dal'),
('black eyed peas', 'proteins', 'weight', 'black eyed peas'),
('eggs', 'proteins', 'count', 'eggs'),
-- Sauces & Condiments
('soy sauce', 'sauces', 'volume', 'soy sauce'),
('dark soy sauce', 'sauces', 'volume', 'dark soy sauce'),
('tamari', 'sauces', 'volume', 'tamari'),
('fish sauce', 'sauces', 'volume', 'fish sauce'),
('oyster sauce', 'sauces', 'volume', 'oyster sauce'),
('hoisin sauce', 'sauces', 'volume', 'hoisin sauce'),
('teriyaki sauce', 'sauces', 'volume', 'teriyaki sauce'),
('worcestershire sauce', 'sauces', 'volume', 'worcestershire sauce'),
('tomato sauce', 'sauces', 'volume', 'tomato sauce'),
('tomato paste', 'sauces', 'weight', 'tomato paste'),
('ketchup', 'sauces', 'volume', 'ketchup'),
('mustard', 'sauces', 'volume', 'mustard'),
('dijon mustard', 'sauces', 'volume', 'dijon mustard'),
('mayonnaise', 'sauces', 'volume', 'mayonnaise'),
('sriracha', 'sauces', 'volume', 'sriracha'),
('chili garlic sauce', 'sauces', 'volume', 'chili garlic sauce'),
('sambal oelek', 'sauces', 'volume', 'sambal oelek'),
('harissa', 'sauces', 'volume', 'harissa'),
('pesto', 'sauces', 'weight', 'pesto'),
('olive oil', 'sauces', 'volume', 'olive oil'),
('vegetable oil', 'sauces', 'volume', 'vegetable oil'),
('canola oil', 'sauces', 'volume', 'canola oil'),
('coconut oil', 'sauces', 'volume', 'coconut oil'),
('sesame oil', 'sauces', 'volume', 'sesame oil'),
('vinegar', 'sauces', 'volume', 'vinegar'),
('apple cider vinegar', 'sauces', 'volume', 'apple cider vinegar'),
('rice vinegar', 'sauces', 'volume', 'rice vinegar'),
('balsamic vinegar', 'sauces', 'volume', 'balsamic vinegar'),
('red wine vinegar', 'sauces', 'volume', 'red wine vinegar'),
('mirin', 'sauces', 'volume', 'mirin'),
('sake', 'sauces', 'volume', 'sake'),
('honey', 'sauces', 'volume', 'honey'),
('maple syrup', 'sauces', 'volume', 'maple syrup'),
('brown sugar', 'sauces', 'weight', 'brown sugar'),
('palm sugar', 'sauces', 'weight', 'palm sugar'),
('jaggery', 'sauces', 'weight', 'jaggery'),
('coconut milk', 'sauces', 'volume', 'coconut milk'),
('coconut cream', 'sauces', 'volume', 'coconut cream'),
('peanut butter', 'sauces', 'weight', 'peanut butter'),
('tahini', 'sauces', 'weight', 'tahini'),
('miso paste', 'sauces', 'weight', 'miso paste'),
-- Other
('sugar', 'other', 'weight', 'sugar'),
('baking powder', 'other', 'weight', 'baking powder'),
('baking soda', 'other', 'weight', 'baking soda'),
('vanilla extract', 'other', 'volume', 'vanilla extract'),
('cornstarch', 'other', 'weight', 'cornstarch'),
('arrowroot', 'other', 'weight', 'arrowroot'),
('gelatin', 'other', 'weight', 'gelatin'),
('yeast', 'other', 'weight', 'yeast'),
('cocoa powder', 'other', 'weight', 'cocoa powder'),
('chocolate', 'other', 'weight', 'chocolate'),
('peanuts', 'other', 'weight', 'peanuts'),
('cashews', 'other', 'weight', 'cashews'),
('almonds', 'other', 'weight', 'almonds'),
('walnuts', 'other', 'weight', 'walnuts'),
('pistachios', 'other', 'weight', 'pistachios'),
('raisins', 'other', 'weight', 'raisins'),
('dates', 'other', 'weight', 'dates'),
('cranberries', 'other', 'weight', 'cranberries'),
('sesame seeds', 'other', 'weight', 'sesame seeds'),
('poppy seeds', 'other', 'weight', 'poppy seeds'),
('chia seeds', 'other', 'weight', 'chia seeds'),
('flax seeds', 'other', 'weight', 'flax seeds'),
('sunflower seeds', 'other', 'weight', 'sunflower seeds'),
('pumpkin seeds', 'other', 'weight', 'pumpkin seeds')
ON CONFLICT (name) DO NOTHING;